name: virtual_scroller
description: >
  A Dart implementation of virtual-scroller by Valdrin Koshi (@valdrinkoshi)
version: 0.0.2
authors:
- John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/apptreesoftware/virtual_scroller
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.1
  meta: ^1.1.6

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  http: ^0.12.0
